-- Коровосчёт v3.1: режим организатора с PIN и сессиями на 30 дней
create table if not exists public.korova_admin_credentials(room_id uuid primary key references korova_rooms(id) on delete cascade,pin_hash text not null,failed_count int not null default 0,locked_until timestamptz,updated_at timestamptz not null default now());
create table if not exists public.korova_admin_sessions(id uuid primary key default gen_random_uuid(),room_id uuid not null references korova_rooms(id) on delete cascade,token_hash bytea not null unique,expires_at timestamptz not null,created_at timestamptz not null default now());
alter table public.korova_admin_credentials enable row level security;alter table public.korova_admin_sessions enable row level security;
revoke all on public.korova_admin_credentials,public.korova_admin_sessions from anon,authenticated;

create or replace function public.korova_set_admin_pin(p_code text,p_pin text) returns void language plpgsql security definer set search_path=public as $$declare r uuid;begin if p_pin!~'^\d{6}$' then raise exception 'PIN должен состоять из 6 цифр';end if;select id into r from korova_rooms where code=korova_normalize_code(p_code);if r is null then raise exception 'Комната не найдена';end if;insert into korova_admin_credentials(room_id,pin_hash) values(r,crypt(p_pin,gen_salt('bf'))) on conflict(room_id) do update set pin_hash=excluded.pin_hash,failed_count=0,locked_until=null,updated_at=now();delete from korova_admin_sessions where room_id=r;end;$$;
revoke all on function public.korova_set_admin_pin(text,text) from public;

create or replace function public.korova_admin_login(p_code text,p_pin text) returns jsonb language plpgsql security definer set search_path=public as $$declare r uuid;c korova_admin_credentials%rowtype;t text;e timestamptz;begin select id into r from korova_rooms where code=korova_normalize_code(p_code);select * into c from korova_admin_credentials where room_id=r;if c.room_id is null then raise exception 'Сначала задайте PIN через Supabase SQL Editor';end if;if c.locked_until>now() then raise exception 'Слишком много попыток. Повторите позже';end if;if crypt(p_pin,c.pin_hash)<>c.pin_hash then update korova_admin_credentials set failed_count=failed_count+1,locked_until=case when failed_count+1>=5 then now()+interval '15 minutes' else null end where room_id=r;raise exception 'Неверный PIN';end if;update korova_admin_credentials set failed_count=0,locked_until=null where room_id=r;t:=encode(gen_random_bytes(32),'hex');e:=now()+interval '30 days';insert into korova_admin_sessions(room_id,token_hash,expires_at) values(r,digest(t,'sha256'),e);delete from korova_admin_sessions where expires_at<now();return jsonb_build_object('token',t,'expiresAt',e);end;$$;
create or replace function public.korova_admin_room(p_code text,p_token text) returns uuid language plpgsql security definer set search_path=public as $$declare r uuid;begin select id into r from korova_rooms where code=korova_normalize_code(p_code);if not exists(select 1 from korova_admin_sessions where room_id=r and token_hash=digest(coalesce(p_token,''),'sha256') and expires_at>now()) then raise exception 'Сессия организатора истекла';end if;return r;end;$$;
revoke all on function public.korova_admin_room(text,text) from public;
grant execute on function public.korova_admin_login(text,text) to anon,authenticated;

create or replace function public.korova_admin_add_player(p_code text,p_token text,p_name text,p_emoji text) returns jsonb language plpgsql security definer set search_path=public as $$begin perform korova_admin_room(p_code,p_token);return korova_add_player(p_code,p_name,p_emoji);end;$$;
create or replace function public.korova_admin_add_existing_player(p_code text,p_token text,p_profile_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$begin perform korova_admin_room(p_code,p_token);return korova_add_existing_player(p_code,p_profile_id);end;$$;
create or replace function public.korova_admin_remove_player(p_code text,p_token text,p_player_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$begin perform korova_admin_room(p_code,p_token);return korova_remove_player(p_code,p_player_id);end;$$;
create or replace function public.korova_admin_update_player_icon(p_code text,p_token text,p_player_id uuid,p_emoji text) returns jsonb language plpgsql security definer set search_path=public as $$begin perform korova_admin_room(p_code,p_token);return korova_update_player_icon(p_code,p_player_id,p_emoji);end;$$;
create or replace function public.korova_admin_finalize_round(p_code text,p_token text) returns jsonb language plpgsql security definer set search_path=public as $$begin perform korova_admin_room(p_code,p_token);return korova_finalize_round(p_code);end;$$;
create or replace function public.korova_admin_update_round(p_code text,p_token text,p_round_id uuid,p_scores jsonb) returns jsonb language plpgsql security definer set search_path=public as $$begin perform korova_admin_room(p_code,p_token);return korova_update_round(p_code,p_round_id,p_scores);end;$$;
create or replace function public.korova_admin_undo_round(p_code text,p_token text) returns jsonb language plpgsql security definer set search_path=public as $$begin perform korova_admin_room(p_code,p_token);return korova_undo_last_round(p_code);end;$$;
create or replace function public.korova_admin_new_game(p_code text,p_token text,p_keep_players boolean) returns jsonb language plpgsql security definer set search_path=public as $$begin perform korova_admin_room(p_code,p_token);return korova_new_game(p_code,p_keep_players);end;$$;
create or replace function public.korova_admin_import_game(p_code text,p_token text,p_played_at timestamptz,p_profiles uuid[],p_rounds jsonb) returns jsonb language plpgsql security definer set search_path=public as $$begin perform korova_admin_room(p_code,p_token);return korova_import_game(p_code,p_played_at,p_profiles,p_rounds);end;$$;
create or replace function public.korova_admin_update_profile(p_code text,p_token text,p_profile_id uuid,p_name text,p_emoji text) returns jsonb language plpgsql security definer set search_path=public as $$declare r uuid;begin r:=korova_admin_room(p_code,p_token);if nullif(trim(p_name),'') is null then raise exception 'Введите имя';end if;update korova_profiles set name=left(trim(p_name),24),emoji=p_emoji,updated_at=now() where id=p_profile_id and room_id=r;if not found then raise exception 'Профиль не найден';end if;update korova_players set name=left(trim(p_name),24),emoji=p_emoji where profile_id=p_profile_id;return korova_get_state(p_code);end;$$;

grant execute on function public.korova_admin_add_player(text,text,text,text),public.korova_admin_add_existing_player(text,text,uuid),public.korova_admin_remove_player(text,text,uuid),public.korova_admin_update_player_icon(text,text,uuid,text),public.korova_admin_finalize_round(text,text),public.korova_admin_update_round(text,text,uuid,jsonb),public.korova_admin_undo_round(text,text),public.korova_admin_new_game(text,text,boolean),public.korova_admin_import_game(text,text,timestamptz,uuid[],jsonb),public.korova_admin_update_profile(text,text,uuid,text,text) to anon,authenticated;
revoke execute on function public.korova_add_player(text,text,text),public.korova_add_existing_player(text,uuid),public.korova_remove_player(text,uuid),public.korova_update_player_icon(text,uuid,text),public.korova_finalize_round(text),public.korova_update_round(text,uuid,jsonb),public.korova_undo_last_round(text),public.korova_new_game(text,boolean),public.korova_import_game(text,timestamptz,uuid[],jsonb) from anon,authenticated;
