-- Коровосчёт v4.0: администрирование архива и профилей
create extension if not exists pgcrypto with schema extensions;
alter function public.korova_set_admin_pin(text,text) set search_path=public,extensions;
alter function public.korova_admin_login(text,text) set search_path=public,extensions;
alter function public.korova_admin_room(text,text) set search_path=public,extensions;

create or replace function public.korova_admin_delete_game(p_code text,p_token text,p_game_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$declare r uuid;begin r:=korova_admin_room(p_code,p_token);delete from korova_games where id=p_game_id and room_id=r and status='archived';if not found then raise exception 'Партия не найдена';end if;return korova_get_state(p_code);end;$$;
create or replace function public.korova_admin_merge_profiles(p_code text,p_token text,p_source uuid,p_target uuid) returns jsonb language plpgsql security definer set search_path=public as $$declare r uuid;begin r:=korova_admin_room(p_code,p_token);if p_source=p_target then raise exception 'Выберите разные профили';end if;if exists(select 1 from korova_games g join korova_players a on a.game_id=g.id and a.profile_id=p_source join korova_players b on b.game_id=g.id and b.profile_id=p_target where g.room_id=r) then raise exception 'Эти игроки встречаются в одной партии — автоматическое объединение невозможно';end if;update korova_players set profile_id=p_target where profile_id=p_source and game_id in(select id from korova_games where room_id=r);delete from korova_profiles where id=p_source and room_id=r;if not found then raise exception 'Профиль не найден';end if;return korova_get_state(p_code);end;$$;
grant execute on function public.korova_admin_delete_game(text,text,uuid),public.korova_admin_merge_profiles(text,text,uuid,uuid) to anon,authenticated;
